#! /bin/sh

bspc monitor eDP1 -d 1 2 3 4 5
bspc monitor HDMI1 -d 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 20
bspc config bottom_padding 20

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a vlc state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a URxvt:Canto-curses state=floating follow=on

xsetroot -cursor_name left_ptr

~/.config/bspwm/displays &
echo $! > ~/.config/bspwm/.displayspid

~/.config/bspwm/restart


#----------------Custom
#Rss feed
urxvt -name "Canto-curses" -e canto-curses
nm-applet &
